Workflow:
  '@WorkflowId': '{e694fbd4-d3fb-f011-840c-0022480972af}'
  '@Name': SCIWorkflow1
  XamlFileName: /workflows/e694fbd4-d3fb-f011-840c-0022480972af/SCIWorkflow1-E694FBD4-D3FB-F011-840C-0022480972AF.xaml
  Type: 1
  Subprocess: 0
  Category: 0
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 1
  TriggerOnDelete: 0
  AsyncAutodelete: 1
  SyncWorkflowLogOnFailure: 0
  StateCode: 0
  StatusCode: 1
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: Account
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': SCIWorkflow1
