Workflow:
  '@WorkflowId': '{5fd06042-b8fb-f011-840c-0022480972af}'
  '@Name': SCIBusinessProcessFlow1
  XamlFileName: /businessprocessflows/5fd06042-b8fb-f011-840c-0022480972af/SCIBusinessProcessFlow1-5FD06042-B8FB-F011-840C-0022480972AF.xaml
  Type: 1
  Subprocess: 0
  Category: 4
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 1
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  processorder: 100
  RunAs: 1
  UniqueName: sci_scibusinessprocessflow1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ProcessTriggerScope: 1
  ModernFlowType: 0
  PrimaryEntity: sci_SCITable1
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': SCIBusinessProcessFlow1
  labels:
    steplabels:
    - '@id': '{e168aa9c-9825-4e0d-a6f5-c4bf34307185}'
      label:
        '@languagecode': 1033
        '@description': Stage1
    - '@id': '{f764b5fa-6890-45c0-a9e1-a512f5bfbb17}'
      label:
        '@languagecode': 1033
        '@description': Step1
    - '@id': '{2d8b0a44-7142-4760-b6bb-4f80b517c788}'
      label:
        '@languagecode': 1033
        '@description': Step2
